### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LGABuster** [tbdscripts/cosmo-gmod#2]
My suggestion will be referring to the Cosmo-web. 

- **_Suggestion_**

- > Add a function to both Store and Forums where you can temporarily shut the store / forum page down within the settings. 

- **_Reasons to add function_**

- > It will help owners/admins edit their website without having to close the entire website for maintenance mode. 

Example- By turning off the store temporarily people can still use the other functions on the website.

**Comment by LGABuster** [comment]
Any reason for it being closed?

**Comment by LucaTanks** [comment]
You opened it on the wrong repository, I didn't comment as you opened an issue in the correct place too
